from .test_select_ranked_customers import *
from .test_join_by_customer_id import *
from .test_customer_count_by_region import *
from .test_customer_data_cleanup import *
from .test_row_number_by_customer_count import *
from .test_apply_region_business_rule import *
from .test_select_customer_id import *
from .test_by_sales_total_desc import *
from .test_distinct_customer_ids import *
from .test_aggregate_sales_by_customer import *